# Generated by Django 5.2.7 on 2025-10-26 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='cars/')),
                ('type', models.CharField(choices=[('Toyota', 'Fortuner'), ('Toyota', 'Corolla'), ('Toyota', 'Camry'), ('Toyota', 'Land Cruiser'), ('Tata', 'Safari'), ('Tata', 'Harrier'), ('Tata', 'Nexon'), ('Hyundai', 'Santro'), ('Hyundai', 'Creta'), ('Hyundai', 'Venue'), ('Hyundai', 'Elantra'), ('Mahindra', 'Scorpio'), ('Mahindra', 'Thar'), ('Mahindra', 'XUV700'), ('Maruti Suzuki', 'Swift'), ('Maruti Suzuki', 'Baleno'), ('Maruti Suzuki', 'Dzire'), ('Honda', 'City'), ('Honda', 'Civic'), ('Honda', 'CR-V'), ('BMW', '3 Series'), ('BMW', '5 Series'), ('BMW', 'X5'), ('Mercedes-Benz', 'C-Class'), ('Mercedes-Benz', 'E-Class'), ('Mercedes-Benz', 'GLE'), ('Audi', 'A4'), ('Audi', 'A6'), ('Audi', 'Q7'), ('Tesla', 'Model S'), ('Tesla', 'Model 3'), ('Tesla', 'Model X'), ('Tesla', 'Model Y'), ('Porsche', '911'), ('Porsche', 'Cayenne'), ('Lamborghini', 'Huracan'), ('Lamborghini', 'Aventador'), ('Ferrari', '488 GTB'), ('Ferrari', 'Portofino'), ('Jaguar', 'XF'), ('Jaguar', 'F-Pace'), ('Land Rover', 'Range Rover'), ('Land Rover', 'Defender')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(default='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
