# Generated by Django 5.2.7 on 2025-10-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cars_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
