# Generated by Django 5.2.7 on 2025-10-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='type',
            field=models.CharField(choices=[('Toyota', 'Fortuner'), ('Toyota', 'Corolla'), ('Toyota', 'Camry'), ('Toyota', 'Land Cruiser'), ('Tata', 'Safari'), ('Tata', 'Harrier'), ('Tata', 'Nexon'), ('Hyundai', 'Santro'), ('Hyundai', 'Creta'), ('Hyundai', 'Venue'), ('Hyundai', 'Elantra'), ('Mahindra', 'Scorpio'), ('Mahindra', 'Thar'), ('Mahindra', 'XUV700'), ('Maruti Suzuki', 'Swift'), ('Maruti Suzuki', 'Baleno'), ('Maruti Suzuki', 'Dzire'), ('Honda', 'City'), ('Honda', 'Civic'), ('Honda', 'CR-V'), ('BMW', '3 Series'), ('BMW', '5 Series'), ('BMW', 'X5'), ('Mercedes-Benz', 'C-Class'), ('Mercedes-Benz', 'E-Class'), ('Mercedes-Benz', 'GLE'), ('Audi', 'A4'), ('Audi', 'A6'), ('Audi', 'Q7'), ('Tesla', 'Model S'), ('Tesla', 'Model 3'), ('Tesla', 'Model X'), ('Tesla', 'Model Y'), ('Porsche', '911'), ('Porsche', 'Cayenne'), ('Lamborghini', 'Huracan'), ('Lamborghini', 'Aventador'), ('Ferrari', '488 GTB'), ('Ferrari', 'Portofino'), ('Jaguar', 'XF'), ('Jaguar', 'F-Pace'), ('Land Rover', 'Range Rover'), ('Land Rover', 'Defender')], max_length=50),
        ),
    ]
